export const config = {
  APPWRITE_PROJECT_ID: import.meta.env.VITE_APPWRITE_PROJECT_ID,
  APPWRITE_ENDPOINT: import.meta.env.VITE_APPWRITE_ENDPOINT,
  APPWRITE_DATABASE_ID: import.meta.env.VITE_APPWRITE_DATABASE_ID,
  APPWRITE_TABLE_ID: import.meta.env.VITE_APPWRITE_TABLE_ID,
};
